### ISSUE TITLE
Another package for polyhedral manipulation

### ISSUE THREAD

**Issue by hnxiao** [blegat/Polyhedra.jl#1]
I just want to bring attentions to another well maintained package PPL (Parma Polyhedra Library).
And a performance comparison with other packages can be found [here] (http://bugseng.com/products/ppl/performance).
It would be great if this package can also be incorporated into this library.

**Comment by blegat** [comment]
Thanks for the notice, that would definitely be nice to have those libraries supported by the library. I have added them in the doc to show the interest. We should maybe ask them in their mailing list whether they would like to make the interface. I see they already have Java/C/OCaml/Prolog interfaces.

**Comment by blegat** [comment]
They have the [APRON](http://apron.cri.ensmp.fr/library/) interface that gives a common interface for NewPolka and PPL but it may be to high level/application specific and not flexible enough for `Polyhedra.jl`.

**Comment by hnxiao** [comment]
Good to know. I'm new to Julia, but I hope I can help one day.

**Comment by blegat** [comment]
Any help would be very much appreciated :)
